config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'}
  resources :users
  get 'unapproved' => 'welcome#unapproved'
  get 'admin' => 'admin#index'
  get 'admin/edit/:id' => 'admin#edituser'
  patch 'admin.:id' => 'admin#updateuser'
  get 'admin/newuser' => 'admin#newuser'
  post 'admin/newuser' => 'admin#createuser'
  get 'admin/show/:id' => 'admin#showuser'
  patch 'admin/approve/:id' => 'admin#approveuser'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :user_params_update, only: [:updateuser]
  before_action :user_params_create, only: [:createuser]
  before_action :authenticate_user! where: :user_type: 'admin'
 

  def index
    @users = User.find_by_sql("SELECT * FROM users WHERE user_type = 'user'")
    @pending_users = User.find_by_sql("SELECT * FROM users WHERE status = 'pending'")
  end

  def showuser
    @user = User.find(params[:id])
  end

  def edituser
    @user = User.find(params[:id])
  end

  def updateuser
    @user = User.find(params[:id])
    if @user.update(user_params_update)
      redirect_to admin_path
    else
      render "/admin/edituser"
    end
  end

  def newuser
    @user = User.new
  end

  def createuser
    @user = User.new(user_params_create)
    if @user.save
      redirect_to admin_path
    else
      render "/admin/newuser"
    end
  end

  def approveuser
    @user = User.find(params[:id])
    @user.status = 'approved'
    @user.save
    redirect_to admin_path
  end

  private

  def user_params_update
    params.require(:user).permit(:full_name)
  end

  def user_params_create
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user.status == "pending"
      unapproved_path
    elsif current_user.user_type == "admin"
      admin_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])    
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def unapproved
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/edituser.html.erb
<h2>Edit</h2>

<%= form_for(@user, url: admin_path(@user.id), method: :patch) do |f| %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name, autofocus: true, autocomplete: "full_name" %>
  </div>  

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


<%= link_to "Back", :back %>

app/views/admin/index.html.erb
<h1>Welcome to the admin dahsboard</h1>
<%=link_to "New User", admin_newuser_path %>
<br/><br/><br/><br/><br/><br/>
All Users: <br>
<%@users.each do |user| %>
email: <%= user.email %> <br/>
status: <%= user.status %><br/>
<%=link_to "Edit", "/admin/edit/#{user.id}"%>
<%=link_to "Show", "/admin/show/#{user.id}"%>
<br><br>
<% end %>
<br><br><br>
Pending:<br>
<%@pending_users.each do |p_user| %>
<%= p_user.email %>
<%=link_to "Approve", "/admin/approve/#{p_user.id}", method: "patch"%>
<br>
<% end %>

app/views/admin/newuser.html.erb
<h2>Sign up</h2>
<%#create account from admin%>
<%= form_for(@user, url: admin_newuser_path, method: :post) do |f| %>
  <%#= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name, autofocus: true, autocomplete: "full_name" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Create Account" %>
  </div>
<% end %>

<%#= render "devise/shared/links" %>

app/views/admin/showuser.html.erb
<br/>
<br/>
full name:<%=@user.full_name %>
<br/>
<br/>
email:<%=@user.email %>
<%=link_to "back", admin_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStockApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%if user_signed_in? %>
    <p>Signed in as <%= current_user.email %></p>
    <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
  <% end %>
  

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to "Sign in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>
<%#= link_to "Edit Profile", edit_user_registration_path%>

app/views/welcome/unapproved.html.erb
<h1>Thanks for signing up, our team will review your registration</h1>
 <%= link_to "Edit Profile", edit_user_registration_path %>